Update build system 	Remove shared library build. utio is too small to benefit from sharing. 	Ensure all object files and the lib go into builddir 	Put builddir in /tmp by default 	Allow setting builddir

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -6,7 +6,7 @@
 ######################################################################
 
 PKG_NAME="utio"
-PKG_VERSTR="v1.3"
+PKG_VERSTR="v1.4"
 PKG_BUGREPORT="Mike Sharov <msharov@users.sourceforge.net>"
 
 # Files that get created by this script
@@ -15,14 +15,6 @@ FILES="Config.mk config.h"
 # Package options
 COMPONENTS='
 {
-name=[without-shared]
-desc=[do not build shared library]
-seds=[s/^\(BUILD_SHARED\)/#\1/]
-}{
-name=[with-static]
-desc=[	build the static library]
-seds=[s/^#\(BUILD_STATIC\)/\1/;s/-fno-enforce-eh-specs/-fno-enforce-eh-specs -ffunction-sections -fdata-sections/;s/-gc-sections/-gc-sections -static-libgcc/;s/@libustl@/@libustl@ -lsupc++/]
-}{
 name=[with-debug]
 desc=[	compile for debugging]
 seds=[s/^#\(DEBUG\)/\1/]
@@ -32,10 +24,10 @@ seds=[s/^#\(DEBUG\)/\1/]
 HEADERS="ustl.h"
 
 # Libraries
-LIBS="ustl"
+LIBS="ustl supc++"
 
 # First pair is used if nothing matches
-PROGS="CC=gcc CXX=g++ LD=ld AR=ar RANLIB=ranlib RANLIB=touch INSTALL=install DOXYGEN=doxygen"
+PROGS="CC=gcc CXX=g++ LD=ld AR=ar RANLIB=ranlib RANLIB=touch INSTALL=install"
 
 # Automatic vars
 [ -d .git ] && PKG_VERSTR=`git describe --always`
@@ -47,7 +39,6 @@ PKG_STRING="$PKG_NAME $PKG_VERSTR"
 CUSTSUBS="s/@PKG_NAME@/$PKG_NAME/g
 s/@PKG_VERSION@/"0x$PKG_MAJOR${PKG_MINOR}"/g
 s/@PKG_VERSTR@/$PKG_VERSTR/g
-s/@PKG_TARNAME@/$PKG_NAME/g
 s/@PKG_STRING@/$PKG_STRING/g
 s/@PKG_UNAME@/`echo $PKG_NAME|tr a-z A-Z`/g
 s/@PKG_BUGREPORT@/$PKG_BUGREPORT/g
@@ -58,7 +49,7 @@ s/@PKG_MINOR@/$PKG_MINOR/g"
 # The rest of the file is configuration code. Leave it alone.	     #
 ######################################################################
 
-die() { rm -f config.sed config.cpu config.cpu.c; exit; }
+die() { rm -f config.sed; exit; }
 
 #### Compile the configurator and generate initial config.sed ########
 
@@ -96,6 +87,7 @@ if [ "$SYSNAME" = "bsd" ]; then
 	s/-Winline/-Wno-inline/g
 	s/#define HAVE_VA_COPY 1/#undef HAVE_VA_COPY/g' >>config.sed
 fi
+[ "$SYSNAME" = "linux" ] || echo 's/-p --ignore-fail-on-non-empty//g' >>config.sed
 if [ "$SYSNAME" = "linux" -o "$SYSNAME" = "bsd" ]; then
     echo 's/@SHBLDFL@/-shared -Wl,-soname=$1/g' >>config.sed
 fi
@@ -108,11 +100,6 @@ if [ "$SYSNAME" = "mac" ]; then
 	s/@SHBLDFL@/-Wl,-single_module -compatibility_version 1 -current_version 1 -install_name $1 -Wl,-Y,1455 -dynamiclib -mmacosx-version-min=10.4/g' >>config.sed
 else
     echo 's/ \?@SYSWARNS@//g' >>config.sed
-fi
-if [ "$SYSNAME" = "mac" ]; then
-    echo 's/#undef \(SIZE_OF_BOOL\)/#define \1 SIZE_OF_LONG/g' >>config.sed
-else
-    echo 's/#undef \(SIZE_OF_BOOL\)/#define \1 SIZE_OF_CHAR/g' >>config.sed
 fi
 
 #### Printing helper functions #######################################
@@ -150,10 +137,7 @@ Installation directories:
   --libdir=DIR		libraries [PREFIX/lib]
   --infodir=DIR		info docs [PREFIX/info]
   --mandir=DIR		man pages [PREFIX/man]
-
-System types:
-  --build=BUILD		compiling on BUILD [guessed]
-  --host=HOST		compiling for HOST [BUILD]
+  --builddir=DIR	location for compiled objects [/tmp/$USER/make]
 "
     PrintComponents
     echo "Report bugs to $PKG_BUGREPORT."
@@ -206,17 +190,16 @@ s/@docdir@/${ac_var_docdir:=$ac_var_datarootdir\/doc\/$PKG_NAME}/g
 s/@infodir@/$ac_var_datarootdir\/info/g
 s/@libdir@/${ac_var_libdir:=$ac_var_prefix\/lib}/g
 s/@mandir@/$ac_var_datarootdir\/man/g
+s/@builddir@/\/tmp\/$USER\/make/g
 s/@gccincludedir@/${ac_var_gccincludedir:=`echo $PINCDIR | sed 's/\//\\\&/g'`}/g
 s/@gcclibdir@/${ac_var_gcclibdir:=`echo $PLIBDIR | sed 's/\//\\\&/g'`}/g
 s/@customincdir@/${ac_var_customincdir:=$ac_var_prefix\/include}/g
 s/@customlibdir@/${ac_var_customlibdir:=$ac_var_prefix\/lib}/g" >>config.sed
 
 if [ "$ac_var_prefix" != "\/usr\/local" -a "$ac_var_prefix" != "\/usr" ]; then
-    echo "s/ \?@CUSTOMINCDIR@/ -I$ac_var_customincdir/g
-s/ \?@CUSTOMLIBDIR@/ -L$ac_var_customlibdir/g" >>config.sed
+    echo "s/ \?@CUSTOMINCDIR@/ -I$ac_var_customincdir/g;s/ \?@CUSTOMLIBDIR@/ -L$ac_var_customlibdir/g" >>config.sed
 else
-    echo "s/ \?@CUSTOMINCDIR@//g
-s/ \?@CUSTOMLIBDIR@//g" >>config.sed
+    echo "s/ \?@CUSTOMINCDIR@//g;s/ \?@CUSTOMLIBDIR@//g" >>config.sed
 fi
 
 #### Find headers, libs, programs, and subs ##########################
@@ -234,7 +217,7 @@ for i in $HEADERS; do
     done
 done
 
-LIBPATH="`echo $LD_LIBRARY_PATH | tr ':' ' '` $ac_var_libdir $ac_var_gcclibdir $ac_var_customlibdir /usr/lib /usr/local/lib /lib"
+LIBPATH="`echo $LD_LIBRARY_PATH | tr ':' ' '` $ac_var_libdir $ac_var_gcclibdir $ac_var_customlibdir /lib /usr/lib /usr/local/lib /usr/lib/x86_64-linux-gnu"
 LIBPATH=`echo $LIBPATH | sed 's/\\\\//g'`
 LIBSUFFIX="so a la dylib"
 for i in $LIBS; do
